services:
  - type: web
    name: subrogation-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        value: your_real_api_key_here
    buildFilter:
      paths:
        - backend/**
    staticPublishPath: backend/static
